/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cipa.telas;
import br.com.cipa.dal.conexao;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import br.com.cipa.dal.conexao;
/**
 *
 * @author debs
 */
public class Login extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    

    public void logar() {
        String sql = "select * from login where login=? and senha=?";
        try {
            String user = this.txtUserCipa.getText();
            pst = conexao.prepareStatement(sql);
            String senha = new String(txtPassCipa.getPassword());
            pst.setString(1, user);
            pst.setString(2, senha);
            rs = pst.executeQuery();

            if (rs.next()) {
                String perfil = rs.getString(6);
                if (perfil.equals("admin")) {
                    MenuPrincipal principal = new MenuPrincipal();
                    principal.setVisible(true);
                    MenuPrincipal.menu.setEnabled(true);
                    MenuPrincipal.menuModVisu.setEnabled(true);
                    MenuPrincipal.menuVoto.setEnabled(true);
                    MenuPrincipal.lblUser.setText(rs.getString(2));
                    MenuPrincipal.lblUser.setForeground(Color.red);
                    this.dispose();
                    conexao.close();
                } else {
                    MenuPrincipal principal = new MenuPrincipal();
                    principal.setVisible(true);
                    MenuPrincipal.menuVoto.setVisible(true);
                    MenuPrincipal.lblUser.setText(rs.getString(2));
                    this.dispose();
                    conexao.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "usuário e/ou senha inválido(s)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public Login() {
        initComponents();
        
        conexao = br.com.cipa.dal.conexao.conector();
        if (conexao != null) {
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("br/com/cipa/imagens/ok.png")));
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("br/com/cipa/imagens/null.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btn_Login = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lbl_status = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserCipa = new javax.swing.JTextField();
        brnLogin = new javax.swing.JButton();
        txtPassCipa = new javax.swing.JPasswordField();
        lbl_status1 = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();

        btnLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLogin.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btn_Login.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLogin1.setText("Usuario");
        getContentPane().add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, -1, -1));

        txtUserCipa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserCipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserCipaActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserCipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 17, 160, 35));

        brnLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        brnLogin.setText("Login");
        brnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(brnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 93, -1, -1));

        txtPassCipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassCipaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassCipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 83, 160, 30));
        getContentPane().add(lbl_status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 124, -1, -1));

        lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/null.png"))); // NOI18N
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed

        // chamando o metodo Logar
        // O botao>evento/Action Performed

    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtUserCipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserCipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserCipaActionPerformed

    private void brnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnLoginActionPerformed

        // chamando o metodo Logar
        logar();
        // O botao>evento/Action Performed

    }//GEN-LAST:event_brnLoginActionPerformed

    private void txtPassCipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassCipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassCipaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnLogin;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnLogin1;
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_status1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JPasswordField txtPassCipa;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserCipa;
    // End of variables declaration//GEN-END:variables
}
